### PR TITLE
Pow

### PR DESCRIPTION
**Pull request by ckormanyos**
The purpose of this PR is to complete `pow()` and its tests.

### CODE REVIEW

**Comment by ckormanyos** [comment]
This one still needs a tad of work since `pow()` has all kinds of special cases and values with its two input params. I'll need another day or two on the mighty `pow()`...

Cc: @mborland

**Comment by ckormanyos** [comment]
> Are you going to keep the other implementation which allowed for Integer powers?

Yes in fact I believe there is an integer power-specified function in the standard. It's like 23 or then again `constexpr` in 26. So there are a couple overloads. We might need review before all is said and done...

grafik

**Comment by ckormanyos** [comment]
But now I'm not sure if the integral power is _until_ C++11 or after, or what happens after 11 to the integral power?

Cc: @mborland

**Comment by ckormanyos** [comment]
>  not sure if the integral power

It the integral power is no longer standard, then we could _make_ _up_ a function. I do this all the time but it's kind of uncomfortable to leave the confines of the standard. Anyway, if I make one up, then I usually call it `pown()` and use the ladder method to compute the powers...

**Comment by mborland** [comment]
> But now I'm not sure if the integral power is _until_ C++11 or after, or what happens after 11 to the integral power?
> 
> 
> 
> Cc: @mborland 

It got replaced by that template overload which allows any arithmetic type to the power of any arithmetic type. In our case I think a template for decimal to the power of a decimal and a template for decimal to an integral power would be it.

**Comment by ckormanyos** [comment]
> It got replaced by that template overload which allows any arithmetic type to the power of any arithmetic type.

Coding delight, ...

> In our case I think a template for decimal to the power of a decimal and a template for decimal to an integral power would be it.

OK, cool. Fits perfectly for me. That's what I had in my original scope of implementation. Let me get the implementation, tests and special parameters right, then we can see if it's _enough_.

**Comment by ckormanyos** [comment]
OK so I finally got `pow(dec, Integral)` and did some refactoring. Now I just need to handle the special cases of `pow(dec, dec)`, then that's all...

**Comment by mborland** [comment]
An optimization step we could take down the is directly manipulating the exponent for powers of ten.

**Comment by ckormanyos** [comment]
> optimization step [...] is directly manipulating the exponent for powers of ten

Nice. I'll note that. See also (renamed) #205.

**Pull request merged**
