### PR TITLE
Tanh128

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by ckormanyos** [comment]
Inrtended to Fix #531

**Comment by ckormanyos** [comment]
Hi @mborland it seems like we have a problem on Ubuntu 18.04 around [here](https://github.com/cppalliance/decimal/actions/runs/8956768642/job/24598965035#step:4:23). Evidently a shared LIB is needed?

I don't know if I should aimlessly start installing stuff or if you already dealt with this one somewhere else?

At first, I thought it was my switch from checkout action v3 to v4 but it's on the runner itself it seems... It feels like a momentary show stopper.

**Comment by mborland** [comment]
> Hi @mborland it seems like we have a problem on Ubuntu 18.04 around [here](https://github.com/cppalliance/decimal/actions/runs/8956768642/job/24598965035#step:4:23). Evidently a shared LIB is needed?
> 
> 
> 
> I don't know if I should aimlessly start installing stuff or if you already dealt with this one somewhere else?
> 
> 
> 
> At first, I thought it was my switch from checkout action v3 to v4 but it's on the runner itself it seems... It feels like a momentary show stopper.

Just leave at actions v3 even though it gives a warning about depreciation. There's a giant thread in the GitHub actions support asking what the fix is and GitHub hasn't responded with anything constructive.

**Comment by ckormanyos** [comment]
I guess it was discussed (among other places) also [here](https://github.com/boostorg/uuid/pull/155). Now I don't know how to clear the cache back to v3?

**Pull request closed without merging**
