### PR TITLE
First few cmath funcs

### PR DESCRIPTION
**Pull request by ckormanyos**
The purpose of this PR is to add the first few cmath functions to `decimal32` such as `frexp`, `ldexp` and a few others. I've tested millions of cases locally and will commit tests with detailed issues I've found soon.

At the moment this is work in progress.

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) when preparing this PR I did discover one mysterious phenomenon. Construction and bit-sets for `decimal32` values $x$ in the tiny band $x \le 8,388,606.5 < 8,388,607.5$ seem to fail. I can provide more info on this and perform more verifications soon.

**Comment by mborland** [comment]
> Hi Matt (@mborland) when preparing this PR I did discover one mysterious phenomenon. Construction and bit-sets for `decimal32` values $x$ in the tiny band $x \le 8,388,606.5 < 8,388,607.5$ seem to fail. I can provide more info on this and perform more verifications soon.

I'm pretty sure that's the point where it moves from continuous bits to assembled with the combination field. If you pull develop I fixed the cross over for the exponent field.

**Comment by ckormanyos** [comment]
See also #45

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) It looks like I still need for you to fire off CI for me, as I'm not yet allowed to execute workflows without permission.

I don't think this one will run green entirely, but it should be better than last, ...

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) this should fix initialization. Down the road we should definitely optimize frexp/ldexp (mul/div powrs-of-two via direct exponent modification if in range).

Also i still have the tiny band about 2^23 blocked out in the RND gen for the tests, This can/will be deleted as we move forward, since it's fixed in develop.

Let's see how this goes and if we cna get the first few funcs in for `decimal32`, ...

Thx Matt.

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) sorry I guess I unexpectedly needed to try another syntax change. Could you please fire this up when you get a chance?

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) do you know why it looks like drone just _stopped_ in the middle of the `test_frexp_ldexp` test?

**Comment by mborland** [comment]
> Hi Matt (@mborland) do you know why it looks like drone just _stopped_ in the middle of one of the `test_frexp_ldexp` ASAN tests?
> 
> 
> 
> It seems like quite a coincidence to stop right in the middle of the new test in this PR?

It looks like the ASAN runs are taking many times longer than the regular ones (as generally expected) and get killed at one hour of run time.

**Comment by ckormanyos** [comment]
> the ASAN runs are taking many times longer 

Ahhh... Good catch. I've got a PP logic somewhere around which I usually use to reduce the scope of testing if ASAN is detected. I'll put that in.

**Comment by ckormanyos** [comment]
Well I did two things on this recent push.

- Add PP-logic to reduce depth on ASAN.
- Introduce `parallel_for()` if desired on those tests handling threading.

Both of these features might be interesting for some other of your/our present/upcoming tests.

**Comment by ckormanyos** [comment]
I'll still need to re-adjust the PP-work on this one a tiny bit more, but it's getting close...

**Comment by ckormanyos** [comment]
Sorry about all the back-and-forth on this one. But it's the first few `<cmath>` funcs, so paving the way for lots to come, ... (I hope).

**Comment by ckormanyos** [comment]
Well Matt (@mborland) it got green.

We will still need to optimize and handle arguments zero, NaN, inf for these functions. But I would actually do that in a second (soon to follow) step.

For now, if you like, at least from my side, this one is good to go for preliminary `frexp`, `ldexp`, `ilogb` and ´pow`.

**Review by mborland — APPROVED** [review]

**Comment by ckormanyos** [comment]
Thanks Matt (@mborland), a solid first start on elementary funcs. I will try to adopt your style 4 spaces and not overly-casting.

**Pull request merged**
