### PR TITLE
Handle pure powers of 10 in pow() function

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) moving forward I noticed a few new tests aren't required in CI for branch protectino. I don't know if that's on purpose or if project evolution exceeded speed of adding the new test to protectin. You might want to update that whole list, ...

grafik

**Comment by mborland** [comment]
> Hi Matt (@mborland) moving forward I noticed a few new tests aren't required in CI for branch protection. I don't know if that's on purpose or if project evolution simply exceeded in its speed the addition of the new tests to branch protection. You might want to update that whole list, ...
> 
> 
> 
> grafik
> 
> 

I've just fallen behind and there's a PR cycling for more CI...

**Comment by ckormanyos** [comment]
Fixes #205

**Comment by ckormanyos** [comment]
> PR cycling for more CI

Right on. I merged that in and re-run mine. Now merged. On to the next funcs.

**Pull request merged**
