### PR TITLE
Start finish gammas but lgamma-128 still needed

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by ckormanyos** [comment]
If/when this cycles, it is intended to handle #381, #431 and #539.

**Comment by ckormanyos** [comment]
Almost forgot this one. But I did forget why it failed to cycle. Merge develop into it with the hope to close. One less issue. Let's let this one cycle through.

CC: @mborland

**Comment by mborland** [comment]
Looks like a slight change of tolerance is needed in order to avoid spurious errors in the future.

**Comment by ckormanyos** [comment]
OK I've added 128-bit for the gammas. It's not a perfect impl. But starting point good.

As we have lots more fundamental problems to address, I'll just adjust test tols and ranges and close the books (temporarily) on gammas until the higher priority tasks are dealt with.

Let's cycle this thingy.

**Comment by mborland** [comment]
Can the tolerances go a bit looser? I'm seeing sporadic failures on CI: https://github.com/cppalliance/decimal/actions/runs/9157848785/job/25175026830#step:4:10586

**Pull request merged**
