### PR TITLE
Update GCC13 runner os

### PR DESCRIPTION
**Pull request by mborland**
Github broke 22.04: https://github.com/actions/runner-images/issues/9866

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) could you please look at the one failed run? It's not getting very far into it. Also a few comments above about `constexpr`-abs.

**Comment by ckormanyos** [comment]
> the one failed run?

Ah I see, the runner is fundamentally flawed at the moment.

**Comment by mborland** [comment]
Since we have GCC 13 covered in Drone I am just going to delete it out of GHA until the fix it

**Comment by ckormanyos** [comment]
Why does stuff like this keep happenin' on such mighty runners???!!! Good choice Matt

**Pull request merged**
