### PR TITLE
Update GDB run in metal CI

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by ckormanyos** [comment]
This PR is intended to handle #759

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) CI metal is up to date and green. But there seems to be a problem on 5 old-ish runner images.

```sh
0s
Post job cleanup.
/usr/bin/docker exec  57bacc[1](https://github.com/cppalliance/decimal/actions/runs/12337976651/job/34432384485#step:15:1)e9454e1a9cc862e1aaf0043bae3458388deb[2](https://github.com/cppalliance/decimal/actions/runs/12337976651/job/34432384485#step:15:2)ae0c6e92e05e0cea1d26 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

**Comment by mborland** [comment]
I can fix that on Monday. We now have to install our own Node because GHA broke it and won't rollback their "upgrades"

**Comment by ckormanyos** [comment]
> fix that on Monday

Thank you Matt (@mborland)

**Pull request merged**
