### PR TITLE
atanh skeleton impl and test

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by ckormanyos** [comment]
This one still needs tests of edge cases, small argument and of course to reach $100$ percent coverage in the `atanh()` implementation.

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) new in today's lineup is the bare-metal CI run, which checks code size and functionality as discussed in another thread. If you get a chance, could you please add the QEMU metal run to the required runs in branch-protection? See image below for naming.

grafik

**Comment by mborland** [comment]
> Hi Matt (@mborland) new in today's lineup is the bare-metal CI run, which checks code size and functionality as discussed in another thread. If you get a chance, could you please add the QEMU metal run to the required runs in branch-protection? See image below for naming.
> 
> grafik

Done

**Comment by ckormanyos** [comment]
CI failing also resulting from [Math 1052](https://github.com/boostorg/math/issues/1052).

**Pull request merged**
