### PR TITLE
More cover files but soon need refined method

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by ckormanyos** [comment]
The purpose of this PR is to add more test files to CodeCov in CI.

Matt (@mborland) I'm looking for some advice on how to improve the situation. I simply listed a few files in the present CodeCov job and manually run these in the `run` part of the step.

I guess the first rudimentary improvement would be to put the working part where all the files are compiled and executed into a shell script.

On the other hand, it is not simply a given that CodeCov should mindlessly simply run all the files in the test folder. It may very well be better to take a combination of some of these compined with a certain _edge_-_cases_ file that picks up the hard-to.reach parts of coverage. Or a combination of these ideas.

Thoughts?

**Comment by mborland** [comment]
Is there someway we can glob the files in the test folder? Compile everything to file_name.exe and then run every exe? I'm not proficient enough in bash to a make that happen, but that's how the cmake tests work.

**Comment by ckormanyos** [comment]
> someway we can glob the files in the test folder? 

Absolutely. CMake or (my preference) GNUmake with a so-called _pattern_ _rule_. I can work this out. In fact, I think we might _like_ this one. When I do this kind of thing, I usually maintain a separate _list_ of files independent from the GNUmake or CMake code so that files can be selectively added/removed from the suite.

One silly problem-ette is that GNUmake and/or CMake can (if files are executed within) shield the CI runner from success/fail of the individual executions. But since we have fuul/deep/multi-compiler handling of the files in the required GHA runners, this is not a big deal.

I'll set up a GNUmake and we can see how it shakes out and if we like it...

**Comment by ckormanyos** [comment]
Hi Matt, I still need to find the best way to exclude the test files without excluding everything. But the recent pushes here bring us up to about $90\%$ line coverage.

**Comment by ckormanyos** [comment]
I'll let it cycle through and push. Then finalize the includes/excludes or find proper code annotations in another round.

**Comment by ckormanyos** [comment]
See also #65

**Pull request merged**
